// Shared public resume content; no private source files are read.
(async function generateResume() {
  const { readFile, writeFile } = await import("node:fs/promises");
  const base = new URL("../", import.meta.url);
  const readJson = async (path) => JSON.parse(await readFile(new URL(path, base), "utf8"));
  const [career, projects, tech] = await Promise.all([
    readJson("src/data/career.json"), readJson("src/data/projects.json"), readJson("src/data/tech-registry.json"),
  ]);
  const esc = (value) => String(value).replace(/\\/g, "\\textbackslash{}")
    .replace(/[&%$#_{}]/g, (c) => "\\" + c).replace(/\^/g, "\\textasciicircum{}")
    .replace(/~/g, "\\textasciitilde{}").replace(/[—–]/g, "--").replace(/·/g, "\\textperiodcentered{}");
  const pattern = [...career.highlights].sort((a,b) => b.length-a.length)
    .map(value => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|");
  const emphasis = (text) => {
    const matcher = new RegExp("(?<![A-Za-z0-9])(" + pattern + ")(?![A-Za-z0-9])", "gi");
    let result = "", cursor = 0;
    for (const match of text.matchAll(matcher)) {
      result += esc(text.slice(cursor, match.index)) + "\\textbf{" + esc(match[0]) + "}";
      cursor = match.index + match[0].length;
    }
    return result + esc(text.slice(cursor));
  };
  const chips = (items) => items.map(item => {
    const known = typeof item === "string" ? tech[item] : null;
    return "\\chip{" + (known ? "tech" + item : "muted") + "}{" + esc(known ? known.label : item.label) + "}";
  }).join("\\hspace{3pt} ");
  const experience = career.experience.map(company => [
    "\\textbf{" + esc(company.name) + "} \\hfill {\\small\\color{muted}" + esc(company.location) + "}\\par",
    ...company.roles.map(role => [
      "\\subsection*{" + esc(role.title) + " \\hfill \\normalfont\\small " + esc(role.start + " - " + role.end) + "}",
      "\\begin{itemize}", ...role.bullets.map(bullet => "\\item " + emphasis(bullet)), "\\end{itemize}",
    ].join("\n")),
  ].join("\n")).join("\n");
  const skillSection = career.resumeSkillGroups.map(group =>
    "\\textbf{\\small " + esc(group.label) + "}\\enspace " + chips(group.items) + "\\par\\vspace{3pt}"
  ).join("\n");
  const selected = career.resumeProjectSlugs.map(slug => {
    const project = projects.find(p => p.slug === slug);
    if (!project) throw new Error("Unknown resume project: " + slug);
    return project;
  });
  const projectSection = selected.map(project => [
    "\\noindent\\textbf{" + esc(project.title) + "}" +
    (project.links.caseStudy ? "\\enspace{\\small\\href{" + career.identity.portfolio + project.links.caseStudy + "}{[Overview]}}" : "") +
    "\\hfill {\\small\\color{muted}" + project.year + "}\\par",
    emphasis(project.resumeDescription || project.description || project.blurb) + "\\par\\vspace{4pt}",
  ].join("\n")).join("\n");
  const education = career.education.map(edu => [
    "\\textbf{" + esc(edu.degree) + "} \\hfill {\\small\\color{muted}" + esc(edu.period) + "}\\par",
    "{\\small\\color{muted}" + esc(edu.institution) + (edu.distinction ? " | " + esc(edu.distinction) : "") + "}\\par\\vspace{3pt}",
  ].join("\n")).join("\n");
  const id = career.identity;
  const source = String.raw`% Generated by npm run resume:source. Edit approved public JSON, not this file.
\documentclass[10pt,letterpaper]{article}
\usepackage[top=0.42in,bottom=0.42in,left=0.55in,right=0.55in]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{enumitem}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{titlesec}
\input{glyphtounicode}
\pdfgentounicode=1
\definecolor{primary}{HTML}{B45309}
\definecolor{foreground}{HTML}{1A1A1A}
\definecolor{muted}{HTML}{57534E}
\definecolor{border}{HTML}{E7E5E4}
` + Object.entries(tech).map(([key, value]) => "\\definecolor{tech" + key + "}{HTML}{" + value.color.replace("#","") + "}").join("\n") + String.raw`
\hypersetup{colorlinks=true,urlcolor=primary,linkcolor=primary,pdftitle={` + esc(id.name + " - Resume") + "},pdfauthor={" + esc(id.name) + String.raw`}}
\titleformat{\section}{\small\bfseries\color{primary}}{}{0em}{\MakeUppercase}[\color{border}\titlerule]
\titlespacing*{\section}{0pt}{7pt}{4pt}
\titleformat{\subsection}{\small\bfseries}{}{0em}{}
\titlespacing*{\subsection}{0pt}{5pt}{2pt}
\setlist[itemize]{leftmargin=1.2em,itemsep=1.5pt,parsep=0pt,topsep=2pt,label=\textbullet}
\setlength{\parindent}{0pt}
\setlength{\fboxsep}{2.2pt}
\setlength{\fboxrule}{0.35pt}
\newcommand{\chip}[2]{\mbox{\fcolorbox{#1!25}{#1!7}{\textcolor{#1}{\sffamily\fontsize{8.5}{10}\selectfont\strut #2}}}}
\hyphenpenalty=10000
\exhyphenpenalty=10000
\raggedbottom
\pagestyle{empty}
\begin{document}
\color{foreground}
{\centering
{\fontsize{23}{25}\selectfont\bfseries ` + esc(id.name) + String.raw`}\par\vspace{4pt}
{\sffamily\small\color{primary}` + esc(id.tagline) + String.raw`}\par\vspace{4pt}
{\small\color{muted}` + esc(id.location) + String.raw`\enspace|\enspace\href{mailto:` + id.email + "}{\\color{muted}" + esc(id.email) + String.raw`}}\par\vspace{3pt}
{\small\href{` + id.portfolio + "}{\\color{muted}" + esc(id.portfolio.replace("https://","")) + String.raw`}\enspace|\enspace\href{` + id.github + String.raw`}{\color{muted}GitHub}\enspace|\enspace\href{` + id.linkedin + String.raw`}{\color{muted}LinkedIn}}\par}
\vspace{3pt}
\section{Summary}
` + emphasis(career.summary) + String.raw`
\section{Experience}
` + experience + String.raw`
\section{Skills}
` + skillSection + String.raw`
\section{Selected Projects}
` + projectSection + String.raw`
\section{Education}
` + education + String.raw`
\section{Awards \& Professional Development}
\textbf{` + esc(career.award.title) + "} (" + career.award.year + String.raw`)\par
` + career.learning.items.map(item => "\\textbf{" + esc(item.name) + "}: " + esc(item.status) + "\\par").join("\n") + String.raw`
\end{document}
`;
  await writeFile(new URL("src/resume/resume.tex", base), source, "utf8");
  console.log("Generated resume source with selective emphasis and text chips.");
})();
